"""
module_atlas.py - Codebase encyclopedia generator for Paloma's Orrery

Scans every .py file in the project directory ONCE and produces TWO files
from that single scan, so they can never diverge from each other again
(L-127, July 2026 -- MODULE_INDEX.md was previously hand-maintained and
drifted 4 months out of date with its own wrong module/line counts,
independent of MODULE_ATLAS.md's own auto-regeneration):

  MODULE_ATLAS.md -- the full reference (deep, for AI upload):
    - Module purpose (docstring or leading comment), full text
    - Public functions with their docstrings
    - Line count, role tag, dependencies, consumers
    - Alphabetical quick-reference index

  MODULE_INDEX.md -- the human-browsable index (light, for GitHub):
    - Same role-based grouping, friendlier section titles
    - One row per module: name + docstring-derived description + lines
    - No function lists / dependency graphs -- that's the atlas's job

Both are MECHANICAL extractions only (no AI synthesis step) -- the index
reads only as good as each module's own docstring. That's a deliberate
tradeoff (L-127): thin docstrings get thin index entries, which is a
visible incentive to improve the docstring rather than hand-patch the
index around it.

Both outputs write to the repo ROOT by default, matching where
MODULE_ATLAS.md already lived and fixing README.md's existing
[MODULE_INDEX.md](MODULE_INDEX.md) link at its root cause (the file used
to live in documentation/, where that root-relative link couldn't reach
it).

Usage:
    python module_atlas.py                     # scan current directory,
                                                # write both files to it
    python module_atlas.py /path/to/project    # scan specific directory
    python module_atlas.py --output atlas.md   # custom atlas filename
    python module_atlas.py --index-output idx.md  # custom index filename
    python module_atlas.py --atlas-only        # skip MODULE_INDEX.md
    python module_atlas.py --index-only        # skip MODULE_ATLAS.md

The atlas is designed to be uploaded to a Claude session as a reference
artifact. Ask Claude natural-language questions and it searches the atlas.
The index is designed to be read directly on GitHub.

Note: Scans only the top-level directory (no subdirectories).
      Run from your clean project directory to avoid picking up
      old copies or virtual environment files.

Module updated: July 2026 with Anthropic's Claude Sonnet 5 (L-127: single
scan now feeds both MODULE_ATLAS.md and the newly-mechanical
MODULE_INDEX.md; both write to repo root).

Module updated: July 2026 with Anthropic's Claude Opus 5 (L-163 Phase 3:
gallery copy of the orrery's module_atlas.py; SCAN_PATHS covers the repo
root plus the four module packages, and the ROLE_MAP mirror starts empty
and regenerates from the gallery's own docstring tags).

Role: devtool
Domain: dev_tools
"""

import ast
import os
import sys
import re
import textwrap
from datetime import datetime
from pathlib import Path


# ============================================================
# ROLE CLASSIFICATION
# ============================================================
# As of L-163 Phase 3 the source of truth is each module's own docstring
# tag, not this dict. ROLE_MAP below is a REGENERATED MIRROR -- a
# readable roster and a name-only fallback -- rewritten from the tags on
# every run. Do not hand-edit it; edit the module's docstring and re-run.

# Sentinel for a module that declares no valid Role. Deliberately not
# 'other': 'other' is a real role a module can choose, while this means
# nobody has said. Collapsing the two would hide the gap.
UNDETERMINED = 'undetermined'

# Directories to scan, relative to the project root. The orrery is flat;
# the gallery copy of this file lists its repo root and module packages.
# Orrery copy uses:
# SCAN_PATHS = ['.']
SCAN_PATHS = ['.', 'tools', 'gallery/assembler',
              'gallery/assembler/harness', 'gallery/assembler/tests']

ROLE_MAP_START = '# ROLE-MAP:START (generated by module_atlas.py -- do not edit this zone by hand)'
ROLE_MAP_END = '# ROLE-MAP:END'

# ROLE-MAP:START (generated by module_atlas.py -- do not edit this zone by hand)
ROLE_MAP = {
    # rendering
    'presentation':                        'rendering',
    'render_events':                       'rendering',
    'render_objects':                      'rendering',
    'render_orbits':                       'rendering',
    'render_spacecraft':                   'rendering',

    # computation
    'resolver':                            'computation',

    # data
    'catalog':                             'data',
    'models':                              'data',

    # cache
    'cache_reader':                        'cache',
    'gallery_cache_builder':               'cache',

    # pipeline
    'assemble':                            'pipeline',

    # utility
    'errors':                              'utility',

    # devtool
    'add_docstrings':                      'devtool',
    'debug_encke_tp':                      'devtool',
    'fingerprint':                         'devtool',
    'gallery_cleanup':                     'devtool',
    'gallery_editor':                      'devtool',
    'gallery_json_fixer':                  'devtool',
    'gallery_maintenance_run':             'devtool',
    'gallery_studio':                      'devtool',
    'inspect_staging':                     'devtool',
    'json_converter':                      'devtool',
    'module_atlas':                        'devtool',
    'serve_gallery':                       'devtool',
    'sweep_report':                        'devtool',
    'test_artifact1_earth':                'devtool',
    'test_gallery_cache_builder_offline':  'devtool',
}
# ROLE-MAP:END


def classify_role(module_name, filepath=None):
    """Classify a module's functional role.

    Reads the module's declared Role: tag. Signature is unchanged for a
    name-only caller (provenance_scanner.py, dep_trace.py) -- pass
    filepath when you already have it and the lookup skips resolution.

    The old filename heuristic is gone: an unrecognized or missing tag
    now returns UNDETERMINED and gets reported, rather than being guessed
    into a role that reads exactly like a declared one.
    """
    role, _domain, _source = classify_module(module_name, filepath)
    return role


def classify_domain(module_name, filepath=None):
    """Read a module's declared Domain: tag. UNDETERMINED if absent."""
    _role, domain, _source = classify_module(module_name, filepath)
    return domain


# ============================================================
# TAG PARSER -- the source of truth as of L-163 Phase 3
# ============================================================
# Every module carries its own classification in its docstring:
#
#     Role: <one of ROLE_ORDER>
#     Domain: <one of the repo's domain vocabulary>
#
# Written by add_docstrings.py (L-163 Phase 2). This section reads them.
# A module that does not declare a valid Role is 'undetermined' -- never
# guessed from its filename. The old _shells suffix heuristic is gone on
# purpose: an inferred role that looks identical to a declared one is a
# claim about provenance that isn't true.

TAG_RE = re.compile(r'^[ \t]*(Role|Domain):[ \t]*(\S+)[ \t]*$', re.MULTILINE)

# Filled in by scan_modules(). Lets classify_role() answer a name-only
# question -- which is how provenance_scanner.py and dep_trace.py ask it --
# without either of them needing to know where the file lives.
_MODULE_PATHS = {}

# Fallback directory for a name-only lookup made before any scan has run.
_TAG_SOURCE_DIR = os.path.dirname(os.path.abspath(__file__))


def set_tag_source_dir(project_dir):
    """Point name-only lookups at a specific directory.

    Only needed by a consumer that runs against a tree other than the one
    this file sits in. scan_modules() calls it automatically.
    """
    global _TAG_SOURCE_DIR
    _TAG_SOURCE_DIR = os.path.abspath(project_dir)


def parse_module_tags(filepath):
    """Read Role:/Domain: out of a module's docstring.

    Returns (role, domain), each either a declared value or
    UNDETERMINED. Uses ast.get_docstring() -- the same call
    get_module_docstring() already makes -- rather than scanning for
    quotes, so a shebang, a comment header, or a quoted string earlier in
    the file cannot be mistaken for the docstring.
    """
    try:
        with open(filepath, 'rb') as handle:
            tree = ast.parse(handle.read())
    except Exception:
        return UNDETERMINED, UNDETERMINED

    doc = ast.get_docstring(tree, clean=False)
    if not doc:
        return UNDETERMINED, UNDETERMINED

    found = dict(TAG_RE.findall(doc))
    role = found.get('Role', UNDETERMINED)
    domain = found.get('Domain', UNDETERMINED)
    if role not in VALID_ROLES:
        role = UNDETERMINED
    return role, domain


def resolve_module_path(module_name):
    """Best guess at where module_name's source lives."""
    if module_name in _MODULE_PATHS:
        return _MODULE_PATHS[module_name]
    return os.path.join(_TAG_SOURCE_DIR, module_name + '.py')


def classify_module(module_name, filepath=None):
    """Classify a module. Returns (role, domain, source).

    Three states, and the source tells you which one you got:

      'tag'          -- the module declares a valid Role. Normal case.
      'legacy'       -- no valid tag, but the regenerated ROLE_MAP mirror
                        still remembers one. Kept for rollout safety; if
                        this fires, a module lost its tag and the atlas
                        says so instead of quietly papering over it.
      'undetermined' -- neither. Reported, never guessed.
    """
    if filepath is None:
        filepath = resolve_module_path(module_name)

    role, domain = parse_module_tags(filepath)
    if role != UNDETERMINED:
        return role, domain, 'tag'

    legacy = ROLE_MAP.get(module_name)
    if legacy in VALID_ROLES:
        return legacy, domain, 'legacy'

    return UNDETERMINED, domain, 'undetermined'


# Role descriptions for the atlas header
ROLE_DESCRIPTIONS = {
    'gui':              'Applications the user launches (GUIs, editors)',
    'pipeline':         'Transforms data between stages (export, conversion, plotting pipelines)',
    'data':             'Catalogs, constants, and static datasets',
    'cache':            'Fetch, store, and retrieve computed data',
    'computation':      'Math, orbital mechanics, data processing',
    'rendering':        'Builds visual traces, figures, and charts',
    'rendering/shells': 'Planetary shell visualizations (sphere layers)',
    'scenario':         'Specific Earth system scenarios',
    'utility':          'Shared helper functions',
    'devtool':          'Developer tools (dependency tracing, atlas)',
    'legacy':           'Archived / superseded modules',
    'other':            'Uncategorized',
    UNDETERMINED:       'No valid Role: tag in the module docstring',
}

# MODULE_INDEX.md section titles -- the same role tags as above, reworded
# for a human skimming the index rather than an AI querying the atlas
# (L-127 Gap item 1: reconcile ROLE_MAP against MODULE_INDEX's existing
# thematic groupings). Deliberately reuses ROLE_MAP as the grouping key
# rather than inventing a second classification scheme -- one source of
# truth for "what kind of module is this," two ways of labeling it.
ROLE_SECTION_TITLES = {
    'gui':              'Core Applications',
    'rendering':        'Visualization Modules',
    'rendering/shells': 'Planetary & Solar Shell Visualizations',
    'computation':      'Orbital Mechanics & Calculations',
    'data':             'Data Catalogs & Constants',
    'cache':            'Cache Management',
    'pipeline':         'Save, Export & Pipeline Utilities',
    'scenario':         'Earth System Scenarios',
    'utility':          'Utility & Helper Modules',
    'devtool':          'Developer Tools',
    'legacy':           'Legacy / Archived Modules',
    'other':            'Other Modules',
    UNDETERMINED:       'Undetermined -- Needs a Role: Tag',
}


# ============================================================
# AST EXTRACTION
# ============================================================

def get_module_docstring(filepath):
    """Extract module-level docstring, falling back to leading comments."""
    try:
        with open(filepath, 'rb') as f:
            source = f.read()
        tree = ast.parse(source)
    except Exception:
        return '(parse error)'

    # Try AST docstring first
    doc = ast.get_docstring(tree)
    if doc:
        # Split into paragraphs
        paras = doc.split('\n\n')
        # Skip paragraphs that are just the filename or a title underline
        meaningful = []
        for p in paras:
            stripped = p.strip()
            # Skip if it's just the filename
            if stripped.replace('.py', '') == os.path.basename(filepath).replace('.py', ''):
                continue
            # Skip if it's just underlines (==== or ----)
            if all(c in '=-' for c in stripped.replace('\n', '')):
                continue
            # Remove inline underline lines from within a paragraph
            clean_lines = []
            for ln in stripped.split('\n'):
                if ln.strip() and not all(c in '=-' for c in ln.strip()):
                    clean_lines.append(ln.strip())
            stripped = ' '.join(clean_lines)
            if not stripped:
                continue
            # Skip if very short and looks like a title
            if len(stripped) < 40 and '\n' not in stripped and not stripped.endswith('.'):
                # Likely a heading -- keep looking but save as fallback
                if not meaningful:
                    meaningful.append(stripped)
                continue
            meaningful.append(stripped)
            break  # Got a real paragraph
        if meaningful:
            # Take up to 300 chars of the best paragraph
            result = meaningful[-1].replace('\n', ' ').strip()
            if len(result) > 300:
                result = result[:297] + '...'
            return result
        # Fallback to first paragraph
        return paras[0].strip().replace('\n', ' ')

    # Fall back to leading comments (lines starting with #)
    try:
        text = source.decode('utf-8', errors='replace')
    except Exception:
        return '(no description)'

    lines = text.split('\n')
    comment_lines = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('#'):
            # Skip shebang
            if stripped.startswith('#!'):
                continue
            content = stripped.lstrip('# ').strip()
            # Skip lines that are just "Import necessary libraries" etc.
            if content.lower().startswith('import '):
                break
            # Skip underline-only lines
            if content and all(c in '=-' for c in content):
                continue
            if content:
                comment_lines.append(content)
        elif stripped == '' and not comment_lines:
            continue  # skip leading blank lines
        elif stripped.startswith('import') or stripped.startswith('from'):
            break  # hit imports, stop
        elif comment_lines:
            break  # hit non-comment after comments
        else:
            break

    if comment_lines:
        return ' '.join(comment_lines)

    return '(no description)'


def get_public_functions(filepath):
    """Extract public function/class names with their docstrings."""
    try:
        with open(filepath, 'rb') as f:
            tree = ast.parse(f.read())
    except Exception:
        return []

    functions = []
    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.FunctionDef) and not node.name.startswith('_'):
            doc = ast.get_docstring(node) or ''
            # First line only
            first_line = doc.split('\n')[0].strip() if doc else ''
            # Get argument names (skip 'self')
            args = []
            for arg in node.args.args:
                name = arg.arg
                if name != 'self':
                    args.append(name)
            sig = f"{node.name}({', '.join(args)})"
            functions.append((sig, first_line, node.lineno))

        elif isinstance(node, ast.ClassDef) and not node.name.startswith('_'):
            doc = ast.get_docstring(node) or ''
            first_line = doc.split('\n')[0].strip() if doc else ''
            functions.append((f"class {node.name}", first_line, node.lineno))

    return functions


def get_local_imports(filepath, local_modules):
    """Extract project-local imports from a Python file."""
    try:
        with open(filepath, 'rb') as f:
            tree = ast.parse(f.read())
    except Exception:
        return set()

    imports = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                base = alias.name.split('.')[0]
                if base in local_modules:
                    imports.add(base)
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                base = node.module.split('.')[0]
                if base in local_modules:
                    imports.add(base)
    return imports


def count_lines(filepath):
    """Count non-blank lines in a file."""
    try:
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            return sum(1 for line in f if line.strip())
    except Exception:
        return 0


# ============================================================
# GRAPH BUILDING
# ============================================================

def iter_module_files(project_dir):
    """Yield (module_name, filepath) for every module under SCAN_PATHS.

    Returns them merged across all scan paths, plus a list of collisions:
    two directories holding the same module name. The orrery scans one
    flat directory and can never collide; the gallery scans five, and a
    silent shadow there would mean the atlas described one file while the
    imports resolved to another.
    """
    found = {}
    collisions = []
    for scan in SCAN_PATHS:
        directory = os.path.join(project_dir, scan)
        if not os.path.isdir(directory):
            print(f"  WARNING: SCAN_PATHS entry not found: {scan}")
            continue
        for name in sorted(os.listdir(directory)):
            if not name.endswith('.py') or name == '__init__.py':
                continue
            full = os.path.join(directory, name)
            if not os.path.isfile(full):
                continue
            mod = name[:-3]
            if mod in found:
                collisions.append((mod, found[mod], full))
                continue
            found[mod] = full
    return found, collisions


def build_dependency_graph(project_dir):
    """Build bidirectional dependency graph for all local modules.

    Module discovery runs through iter_module_files(), so a repo whose
    modules live in package directories (the gallery) is walked the same
    way as a flat one (the orrery).
    """
    paths, collisions = iter_module_files(project_dir)
    local_modules = set(paths)

    for mod, first, second in collisions:
        print(f"  COLLISION: '{mod}' found in two scan paths -- "
              f"{first} and {second}; using the first")

    deps = {}       # module -> set of modules it imports
    consumers = {}  # module -> set of modules that import it

    for mod, fpath in paths.items():
        imported = get_local_imports(fpath, local_modules)
        deps[mod] = imported
        for imp in imported:
            consumers.setdefault(imp, set()).add(mod)

    return deps, consumers, local_modules


# ============================================================
# SCAN -- shared by both generators, run exactly once per invocation
# ============================================================

def scan_modules(project_dir):
    """Scan every .py file in project_dir once and return the list of
    per-module info dicts that both generate_atlas() and generate_index()
    read from. This is the single source of truth both outputs share --
    running this once and handing the same result to both writers is what
    actually prevents the two files from diverging, not just a naming
    convention."""
    print(f"Scanning {project_dir}...")
    set_tag_source_dir(project_dir)
    paths, _collisions = iter_module_files(project_dir)
    _MODULE_PATHS.clear()
    _MODULE_PATHS.update(paths)

    deps, consumers, local_modules = build_dependency_graph(project_dir)

    modules = []
    for mod in sorted(local_modules):
        fpath = paths.get(mod)
        if not fpath or not os.path.exists(fpath):
            continue

        role, domain, source = classify_module(mod, fpath)
        info = {
            'name': mod,
            'path': os.path.relpath(fpath, project_dir).replace(os.sep, '/'),
            'role': role,
            'domain': domain,
            'role_source': source,
            'docstring': get_module_docstring(fpath),
            'functions': get_public_functions(fpath),
            'lines': count_lines(fpath),
            'deps': sorted(deps.get(mod, set())),
            'consumers': sorted(consumers.get(mod, set())),
        }
        modules.append(info)

    return modules


ROLE_ORDER = [
    'gui', 'rendering', 'rendering/shells', 'computation',
    'data', 'cache', 'pipeline', 'scenario', 'utility',
    'devtool', 'legacy', 'other', UNDETERMINED
]

# Every role value must appear in all three structures or a module can be
# classified into a bucket the reports have no heading for, and vanish
# from the output that exists to surface it.
VALID_ROLES = frozenset(r for r in ROLE_ORDER if r != UNDETERMINED)
assert set(ROLE_ORDER) == set(ROLE_DESCRIPTIONS) == set(ROLE_SECTION_TITLES), (
    'ROLE_ORDER / ROLE_DESCRIPTIONS / ROLE_SECTION_TITLES disagree')


# ============================================================
# ATLAS GENERATION
# ============================================================

def regenerate_role_map(modules, source_path=None):
    """Rewrite the ROLE_MAP marker zone in this file from scanned tags.

    ROLE_MAP stopped being the source of truth in L-163 Phase 3 -- the
    docstring tags are. What it still does is give a name-only consumer
    something to fall back on, and give a human a readable roster without
    opening 114 files. So it is regenerated, never hand-edited, using the
    same START/END marker-zone pattern ledger_index.py uses for its INDEX.

    Only modules whose role came from a real tag are written. A module
    that is undetermined is left out rather than frozen into the mirror,
    so a missing tag stays visible instead of curing itself on the next
    run.
    """
    if source_path is None:
        source_path = os.path.abspath(__file__)

    tagged = [m for m in modules if m.get('role_source') == 'tag']
    if not tagged:
        print("  ROLE_MAP: nothing tagged; zone left untouched")
        return False

    width = max(len(m['name']) for m in tagged) + 4
    lines = [ROLE_MAP_START, 'ROLE_MAP = {']
    for role in ROLE_ORDER:
        members = [m for m in tagged if m['role'] == role]
        if not members:
            continue
        lines.append(f'    # {role}')
        for m in sorted(members, key=lambda x: x['name']):
            key = "'" + m['name'] + "':"
            lines.append(f"    {key:<{width}} '{role}',")
        lines.append('')
    if lines[-1] == '':
        lines.pop()
    lines.append('}')
    lines.append(ROLE_MAP_END)
    zone = '\n'.join(lines)

    with open(source_path, 'rb') as handle:
        raw = handle.read()
    ending = b'\r\n' if b'\r\n' in raw else b'\n'
    text = raw.decode('utf-8').replace('\r\n', '\n')

    if (ROLE_MAP_START + '\n') not in text or ('\n' + ROLE_MAP_END) not in text:
        print("  ROLE_MAP: markers not found; zone NOT regenerated")
        return False

    # Anchored at line start on purpose. This file DEFINES the marker
    # strings, so the marker text also appears inside a quoted constant
    # near the top -- an unanchored match would start there and eat the
    # definitions along with the zone.
    pattern = (r'^' + re.escape(ROLE_MAP_START) + r'$.*?^'
               + re.escape(ROLE_MAP_END) + r'$')
    new_text = re.sub(pattern, lambda _m: zone, text,
                      flags=re.DOTALL | re.MULTILINE)
    if new_text == text:
        print(f"  ROLE_MAP: already current ({len(tagged)} modules)")
        return False

    out = new_text.replace('\n', ending.decode('ascii'))
    with open(source_path, 'wb') as handle:
        handle.write(out.encode('utf-8'))
    print(f"  ROLE_MAP: regenerated from tags ({len(tagged)} modules)")
    return True


def classification_report_lines(modules, heading_level='##'):
    """Markdown block naming every module the classifier could not place.

    Exists so an undetermined module is visible in the documents people
    actually read, not just in console output that scrolls past. Silence
    here is the success case: when every module carries a valid tag the
    block says so in one line rather than disappearing, because a section
    that vanishes when clean is indistinguishable from one that broke.
    """
    undetermined = [m for m in modules if m['role'] == UNDETERMINED]
    legacy = [m for m in modules if m.get('role_source') == 'legacy']
    no_domain = [m for m in modules
                 if m.get('domain', UNDETERMINED) == UNDETERMINED]

    out = [f'{heading_level} Classification Coverage', '']
    if not undetermined and not legacy and not no_domain:
        out.append(f'All {len(modules)} modules declare a valid `Role:` and '
                   '`Domain:` tag in their docstring.')
        out.append('')
        return out

    if undetermined:
        out.append(f'**Undetermined role ({len(undetermined)}).** No valid '
                   '`Role:` tag in the module docstring. Not guessed -- add '
                   'the tag and re-run `add_docstrings.py`, then this file.')
        out.append('')
        for m in undetermined:
            out.append(f'- `{m["path"]}`')
        out.append('')

    if legacy:
        out.append(f'**Legacy fallback ({len(legacy)}).** No valid tag, but '
                   'the regenerated `ROLE_MAP` mirror still remembered a '
                   'role. These modules lost a tag they used to have.')
        out.append('')
        for m in legacy:
            out.append(f'- `{m["path"]}` -- fell back to `{m["role"]}`')
        out.append('')

    if no_domain:
        out.append(f'**Undetermined domain ({len(no_domain)}).** No valid '
                   '`Domain:` tag.')
        out.append('')
        for m in no_domain:
            out.append(f'- `{m["path"]}`')
        out.append('')

    return out


def generate_atlas(modules, output_path):
    """Write MODULE_ATLAS.md from an already-scanned modules list
    (see scan_modules)."""

    # Group by role
    by_role = {}
    for mod in modules:
        role = mod['role']
        by_role.setdefault(role, []).append(mod)

    # Count totals
    total_lines = sum(m['lines'] for m in modules)
    total_functions = sum(len(m['functions']) for m in modules)

    # Generate markdown
    lines = []
    now = datetime.now().strftime('%B %d, %Y')

    lines.append("# Paloma's Orrery -- Module Atlas")
    lines.append("")
    lines.append(f"Generated: {now}")
    lines.append(f"Modules: {len(modules)} | "
                 f"Functions: {total_functions} | "
                 f"Lines: {total_lines:,}")
    lines.append("")
    lines.extend(classification_report_lines(modules))
    lines.append("---")
    lines.append("")
    lines.append("## How to Use This Document")
    lines.append("")
    lines.append("Upload this file to a Claude session. Then ask questions:")
    lines.append("")
    lines.append('- "What modules are involved in rendering comets?"')
    lines.append('- "I want to add a new spacecraft encounter -- what do I touch?"')
    lines.append('- "What imports spacecraft_encounters and what does it import?"')
    lines.append('- "Show me the pipeline from GUI click to rendered figure"')
    lines.append('- "What would break if I changed constants_new?"')
    lines.append("")
    lines.append("Claude searches this atlas, reads relevant source files,")
    lines.append("and explains in context.")
    lines.append("")
    lines.append("For a lighter, human-browsable version of this same scan, see")
    lines.append("MODULE_INDEX.md (also generated by this script).")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Role summary table
    lines.append("## Roles at a Glance")
    lines.append("")
    lines.append("| Role | Count | Description |")
    lines.append("|------|-------|-------------|")
    for role in ROLE_ORDER:
        if role in by_role:
            desc = ROLE_DESCRIPTIONS.get(role, '')
            count = len(by_role[role])
            lines.append(f"| {role} | {count} | {desc} |")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Module entries grouped by role
    for role in ROLE_ORDER:
        if role not in by_role:
            continue

        role_desc = ROLE_DESCRIPTIONS.get(role, role)
        role_modules = by_role[role]

        lines.append(f"## {role.upper()}: {role_desc}")
        lines.append("")

        for mod in role_modules:
            lines.append(f"### {mod['name']}.py")
            lines.append("")
            lines.append(f"**Role:** {mod['role']} | "
                         f"**Lines:** {mod['lines']:,}")
            lines.append("")

            # Description
            lines.append(f"> {mod['docstring']}")
            lines.append("")

            # Dependencies
            if mod['deps']:
                lines.append(f"**Depends on:** "
                             f"{', '.join(mod['deps'])}")
            else:
                lines.append("**Depends on:** (none)")

            # Consumers
            if mod['consumers']:
                lines.append(f"**Consumed by:** "
                             f"{', '.join(mod['consumers'])}")
            else:
                lines.append("**Consumed by:** (none -- standalone)")

            lines.append("")

            # Public functions
            if mod['functions']:
                lines.append("**Public functions:**")
                lines.append("")
                for sig, doc, lineno in mod['functions']:
                    if doc:
                        lines.append(f"- `{sig}` (line {lineno}) -- {doc}")
                    else:
                        lines.append(f"- `{sig}` (line {lineno})")
                lines.append("")

            lines.append("---")
            lines.append("")

    # Alphabetical quick-reference index at the end
    lines.append("## Alphabetical Index")
    lines.append("")
    lines.append("| Module | Role | Lines | Deps | Consumers |")
    lines.append("|--------|------|------:|-----:|----------:|")
    for mod in sorted(modules, key=lambda m: m['name']):
        lines.append(
            f"| {mod['name']} | {mod['role']} | "
            f"{mod['lines']:,} | {len(mod['deps'])} | "
            f"{len(mod['consumers'])} |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by module_atlas.py -- "
                 "Paloma's Orrery Developer Tools*")
    lines.append("")

    # Write output
    content = '\n'.join(lines)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Atlas written to {output_path}")
    print(f"  {len(modules)} modules, {total_functions} functions, "
          f"{total_lines:,} lines")

    # Print role summary
    print("\nRole summary:")
    for role in ROLE_ORDER:
        if role in by_role:
            count = len(by_role[role])
            print(f"  {role:20s} {count:3d} modules")


# ============================================================
# INDEX GENERATION (L-127: mechanical, same scan as the atlas)
# ============================================================

def _index_description(mod):
    """The docstring text for an index row, with a redundant leading
    'modulename.py - ' prefix stripped (many docstrings restate the
    filename as their first words -- harmless in the atlas's blockquote
    format, repetitive next to a Module column that already says it)."""
    doc = mod['docstring']
    prefix_patterns = [
        mod['name'] + '.py - ', mod['name'] + '.py -',
        mod['name'] + '.py: ', mod['name'] + '.py ',
        mod['name'] + ' - ', mod['name'] + ' -',
    ]
    for p in prefix_patterns:
        if doc.startswith(p):
            doc = doc[len(p):].lstrip()
            break
    return doc[:1].upper() + doc[1:] if doc else doc


def generate_index(modules, output_path):
    """Write MODULE_INDEX.md from the SAME already-scanned modules list
    generate_atlas() uses -- a lighter, human-browsable companion, not an
    independent document. Mechanical only: each module's description is
    its own docstring (via scan_modules -> get_module_docstring), not an
    AI-synthesized summary. A thin docstring makes a thin index entry --
    deliberate, per L-127: that's a visible incentive to improve the
    docstring, not a reason to hand-patch the index around it."""

    by_role = {}
    for mod in modules:
        by_role.setdefault(mod['role'], []).append(mod)

    total_lines = sum(m['lines'] for m in modules)
    total_functions = sum(len(m['functions']) for m in modules)

    lines = []
    now = datetime.now().strftime('%B %d, %Y')

    lines.append("# Paloma's Orrery - Module Index")
    lines.append("")
    lines.append(f"**Generated:** {now} by `module_atlas.py`  ")
    lines.append("**Repository:** Paloma's Orrery - Solar System Visualization Suite  ")
    lines.append("**Philosophy:** Data Preservation is Climate Action")
    lines.append("")
    lines.append("This file and `MODULE_ATLAS.md` are generated from the SAME scan")
    lines.append("(see `module_atlas.py`) -- they cannot diverge from each other the")
    lines.append("way the old hand-maintained MODULE_INDEX.md did. This is the light,")
    lines.append("human-browsable view; `MODULE_ATLAS.md` is the deep reference")
    lines.append("(functions, dependencies, consumers) meant for AI-assisted queries.")
    lines.append("")
    lines.append(f"**Total Python Files:** {len(modules)}  ")
    lines.append(f"**Total Lines of Code (non-blank):** {total_lines:,}  ")
    lines.append(f"**Total Public Functions/Classes:** {total_functions:,}")
    lines.append("")
    lines.extend(classification_report_lines(modules))
    lines.append("")
    lines.append("---")
    lines.append("")

    for role in ROLE_ORDER:
        if role not in by_role:
            continue
        title = ROLE_SECTION_TITLES.get(role, role.title())
        role_modules = sorted(by_role[role], key=lambda m: m['name'])

        lines.append(f"## {title}")
        lines.append("")
        lines.append("| Module | Description |")
        lines.append("|--------|-------------|")
        for mod in role_modules:
            desc = _index_description(mod).replace('|', '\\|')
            lines.append(
                f"| `{mod['name']}.py` | {desc} ({mod['lines']:,} lines) |"
            )
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("*Generated by `module_atlas.py` -- Paloma's Orrery Developer Tools. "
                 "For function-level detail, dependencies, and consumers, see "
                 "`MODULE_ATLAS.md`.*")
    lines.append("")

    content = '\n'.join(lines)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Index written to {output_path}")


# ============================================================
# MAIN
# ============================================================

def main():
    project_dir = '.'
    atlas_path = 'MODULE_ATLAS.md'
    index_path = 'MODULE_INDEX.md'
    do_atlas = True
    do_index = True

    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] == '--output' and i + 1 < len(args):
            atlas_path = args[i + 1]
            i += 2
        elif args[i] == '--index-output' and i + 1 < len(args):
            index_path = args[i + 1]
            i += 2
        elif args[i] == '--atlas-only':
            do_index = False
            i += 1
        elif args[i] == '--index-only':
            do_atlas = False
            i += 1
        elif not args[i].startswith('-'):
            project_dir = args[i]
            i += 1
        else:
            i += 1

    if not os.path.isdir(project_dir):
        print(f"ERROR: '{project_dir}' is not a directory")
        sys.exit(1)

    modules = scan_modules(project_dir)

    # ROLE_MAP is a mirror of the tags now, so refresh it from this scan
    # before writing the reports. Hand-editing it is what Phase 3 retired.
    regenerate_role_map(modules)

    if do_atlas:
        generate_atlas(modules, atlas_path)
    if do_index:
        generate_index(modules, index_path)


if __name__ == '__main__':
    main()
